# Generated by Django 4.2.7 on 2023-11-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_number', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_description', models.CharField(max_length=250)),
                ('product_pictures', models.FileField(upload_to='')),
                ('product_qte', models.IntegerField()),
                ('product_date_build', models.CharField(max_length=20)),
                ('product_date_expiration', models.CharField(max_length=20)),
            ],
        ),
    ]
